// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkBvHYukFBDHOnPisCwEHfTAt1ZrokHpM',
    appId: '1:27527280535:web:41fe6242e7ea5bd944f6d2',
    messagingSenderId: '27527280535',
    projectId: 'glucotrack-88515',
    authDomain: 'glucotrack-88515.firebaseapp.com',
    storageBucket: 'glucotrack-88515.firebasestorage.app',
    measurementId: 'G-BGGWHT22TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcwFWPtHftASH-5ArCzAHO3Y3xxLFAdS0',
    appId: '1:27527280535:android:e111b177f50919fe44f6d2',
    messagingSenderId: '27527280535',
    projectId: 'glucotrack-88515',
    storageBucket: 'glucotrack-88515.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfJ52MBzXSKr7NOu3RkOm0cyXAKU2deuk',
    appId: '1:27527280535:ios:53b7285c2896f63d44f6d2',
    messagingSenderId: '27527280535',
    projectId: 'glucotrack-88515',
    storageBucket: 'glucotrack-88515.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfJ52MBzXSKr7NOu3RkOm0cyXAKU2deuk',
    appId: '1:27527280535:ios:53b7285c2896f63d44f6d2',
    messagingSenderId: '27527280535',
    projectId: 'glucotrack-88515',
    storageBucket: 'glucotrack-88515.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkBvHYukFBDHOnPisCwEHfTAt1ZrokHpM',
    appId: '1:27527280535:web:c51d80d92cbb218744f6d2',
    messagingSenderId: '27527280535',
    projectId: 'glucotrack-88515',
    authDomain: 'glucotrack-88515.firebaseapp.com',
    storageBucket: 'glucotrack-88515.firebasestorage.app',
    measurementId: 'G-MEX06P01SY',
  );
}
